project:
  type: website
  output-dir: docs

website:
  title: "Cultivo de caña (Saccharum officinarum)"

  navbar:
    background: "#153768"
    align: center
    title: false
    collapse-below: lg

    left:
      - text: "Inicio"
        icon: house-door-fill
        menu:
          - text: "Portada"
            href: index.qmd

          - text: "Integrantes"
            href: integrantes.qmd

          - text: "Cultivo"
            href: cultivo.qmd

      - text: "Introducción"
        href: introduccion.qmd

      - text: "Materiales y Métodos"
        href: metodologia.qmd

      - text: "Resultados y discusiones"
        href: resultados.qmd

      - text: "Conclusiones"
        href: conclusiones.qmd

      - text: "Referencias"
        href: referencias.qmd
      
      - text: "Anexos"
        href: anexos.qmd


    right:
      - icon: github
        href: https://github.com/7342664321-bot/Saccharum-officinarum_ca-a 
        aria-label: GitHub

  page-footer:
    left: "Página creada con Quarto"
    background: "#153768"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    number-sections: false
    code-copy: true